"""add_audit_logs_columns

Revision ID: c4c80453a30d
Revises: bb19837c3368
Create Date: 2026-07-05 01:39:37.956439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4c80453a30d'
down_revision: Union[str, Sequence[str], None] = 'bb19837c3368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenter_webhook_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False, comment='Unique event ID from Paymenter for idempotency'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Event type (e.g. user.created, payment.succeeded)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Raw event payload from Paymenter'),
    sa.Column('signature', sa.String(length=512), nullable=False, comment='HMAC-SHA256 signature from the request'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Whether the event has been processed'),
    sa.Column('processing_attempts', sa.Integer(), nullable=False, comment='Number of processing attempts'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message if processing failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paymenter_user_id', sa.String(length=255), nullable=True, comment='Paymenter user ID from the event for cross-reference'),
    sa.Column('paymenter_order_id', sa.String(length=255), nullable=True, comment='Paymenter order ID from the event for cross-reference'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenter_webhook_events_event_id'), 'paymenter_webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_paymenter_webhook_events_event_type'), 'paymenter_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_paymenter_webhook_events_paymenter_order_id'), 'paymenter_webhook_events', ['paymenter_order_id'], unique=False)
    op.create_index(op.f('ix_paymenter_webhook_events_paymenter_user_id'), 'paymenter_webhook_events', ['paymenter_user_id'], unique=False)
    op.create_table('abuse_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('service_id', sa.String(length=255), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_reports_reporter_id'), 'abuse_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_abuse_reports_service_id'), 'abuse_reports', ['service_id'], unique=False)
    op.create_index(op.f('ix_abuse_reports_severity'), 'abuse_reports', ['severity'], unique=False)
    op.create_index(op.f('ix_abuse_reports_status'), 'abuse_reports', ['status'], unique=False)
    op.create_index(op.f('ix_abuse_reports_type'), 'abuse_reports', ['type'], unique=False)
    op.create_index(op.f('ix_abuse_reports_user_id'), 'abuse_reports', ['user_id'], unique=False)
    op.create_table('traffic_usage',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['vpn_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_usage_account_id'), 'traffic_usage', ['account_id'], unique=False)
    op.drop_index('ix_dns_records_profile_id', table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index('ix_smartdns_profiles_geo_region', table_name='smartdns_profiles')
    op.drop_index('ix_smartdns_profiles_pdns_zone_id', table_name='smartdns_profiles')
    op.drop_index('ix_smartdns_profiles_service_id', table_name='smartdns_profiles')
    op.drop_index('ix_smartdns_profiles_status', table_name='smartdns_profiles')
    op.drop_table('smartdns_profiles')
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.drop_constraint('fk_audit_logs_user_id_users', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_tenant_id_tenants', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'success')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'actor_role')
    op.drop_column('audit_logs', 'changes')
    op.drop_index('ix_invoices_user_status', table_name='invoices')
    op.drop_constraint('fk_invoices_service_id_services', 'invoices', type_='foreignkey')
    op.drop_constraint('fk_invoices_user_id_users', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_products_module_active', table_name='products', postgresql_where='(active = true)')
    op.alter_column('reseller_commissions', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_reseller_commissions_status', table_name='reseller_commissions')
    op.drop_index('ix_services_expiry', table_name='services')
    op.drop_index('ix_services_tenant_status', table_name='services')
    op.drop_index('ix_services_user_status', table_name='services')
    op.drop_constraint('fk_services_tenant_id_tenants', 'services', type_='foreignkey')
    op.drop_constraint('fk_services_product_id_products', 'services', type_='foreignkey')
    op.drop_constraint('fk_services_user_id_users', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'services', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_tenant_pricing_unique', table_name='tenant_product_pricing')
    op.drop_index('ix_transactions_user_type', table_name='transactions')
    op.drop_constraint('fk_transactions_user_id_users', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'paymenter_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_constraint('fk_users_tenant_id_tenants', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # برای ستون protocol

    op.drop_index('ix_vpn_accounts_protocol_status', table_name='vpn_accounts')
    op.drop_index('ix_vpn_protocol_configs_account_key', table_name='vpn_protocol_configs')
    op.add_column('vpn_servers', sa.Column('protocol', sa.String(length=20), nullable=False))
    op.add_column('vpn_servers', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('vpn_servers', sa.Column('ssh_port', sa.Integer(), nullable=False))
    op.add_column('vpn_servers', sa.Column('ssh_user', sa.String(length=100), nullable=False))
    op.add_column('vpn_servers', sa.Column('ssh_key_path', sa.String(length=512), nullable=True))
    op.add_column('vpn_servers', sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_vpn_servers_country', table_name='vpn_servers')
    op.drop_index('ix_vpn_servers_is_active_country', table_name='vpn_servers')
    op.drop_index('ix_vpn_servers_is_active_current_clients', table_name='vpn_servers')
    op.create_index(op.f('ix_vpn_servers_protocol'), 'vpn_servers', ['protocol'], unique=False)
    op.create_index(op.f('ix_vpn_servers_status'), 'vpn_servers', ['status'], unique=False)
